package app;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

public final class PlyWriter {
    private PlyWriter() {
    }

    public static void write(PlyMesh mesh, Path output, String format) throws IOException {
        Path parent = output.toAbsolutePath().getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }

        try (OutputStream out = Files.newOutputStream(output)) {
            StringBuilder header = new StringBuilder();
            header.append("ply\n");
            header.append("format ").append(format).append(" 1.0\n");
            header.append("comment Generated by InnerShellGenerator\n");
            header.append("element vertex ").append(mesh.vertexCount()).append("\n");
            for (VertexProperty prop : mesh.vertexProperties()) {
                header.append("property ").append(prop.type().plyName()).append(' ').append(prop.name()).append("\n");
            }
            header.append("element face ").append(mesh.faceCount()).append("\n");
            header.append("property list uchar int vertex_indices\n");
            header.append("end_header\n");
            out.write(header.toString().getBytes(StandardCharsets.US_ASCII));

            if (format.equals("ascii")) {
                writeAscii(mesh, out);
            } else {
                writeBinary(mesh, out);
            }
        }
    }

    private static void writeAscii(PlyMesh mesh, OutputStream out) throws IOException {
        for (int i = 0; i < mesh.vertexCount(); i++) {
            StringBuilder row = new StringBuilder();
            for (int p = 0; p < mesh.vertexProperties().size(); p++) {
                VertexProperty prop = mesh.vertexProperties().get(p);
                if (p > 0) {
                    row.append(' ');
                }
                row.append(prop.type().formatAscii(mesh.vertexValues().get(prop.name())[i]));
            }
            row.append('\n');
            out.write(row.toString().getBytes(StandardCharsets.US_ASCII));
        }

        for (int i = 0; i < mesh.faceCount(); i++) {
            String row = "3 " + mesh.faces()[i * 3] + " " + mesh.faces()[i * 3 + 1] + " " + mesh.faces()[i * 3 + 2] + "\n";
            out.write(row.getBytes(StandardCharsets.US_ASCII));
        }
    }

    private static void writeBinary(PlyMesh mesh, OutputStream out) throws IOException {
        ByteArrayOutputStream vertexBytes = new ByteArrayOutputStream();
        for (int i = 0; i < mesh.vertexCount(); i++) {
            for (VertexProperty prop : mesh.vertexProperties()) {
                prop.type().write(vertexBytes, mesh.vertexValues().get(prop.name())[i]);
            }
        }
        out.write(vertexBytes.toByteArray());

        ByteBuffer bb = ByteBuffer.allocate(mesh.faceCount() * (1 + 3 * 4)).order(ByteOrder.LITTLE_ENDIAN);
        for (int i = 0; i < mesh.faceCount(); i++) {
            bb.put((byte) 3);
            bb.putInt(mesh.faces()[i * 3]);
            bb.putInt(mesh.faces()[i * 3 + 1]);
            bb.putInt(mesh.faces()[i * 3 + 2]);
        }
        out.write(bb.array());
    }
}
